Resources:
  RecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: recipeId
          AttributeType: N
        - AttributeName: userId
          AttributeType: S
      # BillingMode: String
      GlobalSecondaryIndexes:
        - IndexName: recipesGlobalSecondaryIndex
          KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: recipeId
            KeyType: RANGE
          Projection:
            # NonKeyAttributes:
            # - recipeId
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      KeySchema:
        - AttributeName: recipeId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      # LocalSecondaryIndexes:
        # - LocalSecondaryIndex
      # PointInTimeRecoverySpecification:
        # PointInTimeRecoverySpecification
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      # SSESpecification:
        # SSESpecification
      # StreamSpecification:
        # StreamSpecification
      TableName: ${self:custom.recipesTableName}
      # Tags:
        # - Tag
      # TimeToLiveSpecification:
        # TimeToLiveSpecification
